"""
Resolve legacy YAML-package entity ids for fields opted into legacy naming.

Reads ``legacy_entity_map.json`` (generated by
``scripts/generate_legacy_entity_map.py`` from the legacy YAML package's
register map -- see ``dev/legacy_reference/README.md``) so that, when a
config entry has ``CONF_LEGACY_NAMING`` set, ``entity.py`` can claim the same
``entity_id`` the legacy package used for a given field. Recorder history is
keyed by ``entity_id``, not ``unique_id``, so this is the only thing that
needs to match for history/dashboards/automations to keep working.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_MAP_PATH = Path(__file__).parent / "legacy_entity_map.json"


@lru_cache(maxsize=1)
def _load_map() -> dict[str, list[dict[str, Any]]]:
    return json.loads(_MAP_PATH.read_text(encoding="utf-8"))


def suggested_object_id_for(key: str, platform: str) -> str | None:
    """
    Return the legacy object id (entity_id minus the domain) for a field.

    ``platform`` disambiguates fields with more than one legacy candidate
    (e.g. a controls field the legacy package exposed as both a raw
    diagnostic sensor and a switch) -- only a candidate whose domain matches
    the platform actually creating this entity is usable.
    """
    for candidate in _load_map().get(key, []):
        if candidate["domain"] == platform:
            return candidate["entity_id"].split(".", 1)[1]
    return None


def all_legacy_entity_ids() -> set[str]:
    """Every legacy entity_id across the whole map, for a registry pre-check."""
    return {
        candidate["entity_id"]
        for candidates in _load_map().values()
        for candidate in candidates
    }
